### ISSUE TITLE
Reward model training implementation fails

### ISSUE THREAD

**Issue by Elysia-afk** [thunlp/ProactiveAgent#21]
Hello. The following is my training script for the reward model, which follows the setting in the paper（also 8 A100 GPUs).  By the way, I used at most 20 min to finish training, but you report 1.5 h, which is weird.

My average statistics for MN, NR, CD& FD are 0.59, 0.54, 0.57, 0.74 , it seems to be a large gap to your result. 
Would you mind pointing out the different parts or unveiling your training setting, thx. 

```train_reward.yaml

### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: /dataset/reward_data/
dataset: trainset_reward_llama
template: llama3
cutoff_len: 2048
max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b_sft/full/sft
logging_steps: 10
save_steps: 28
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-5                                         
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
save_only_model: true
```

**Comment by luyaxi** [comment]
There are several problems with your configuration:
1. The `cutoff_len` should be set to `8196` to avoid cut-off (Though some data may exceed the 8196 limitation).
2. Try to enlarge the `max_samples` if the trainset contains more than 2000 samples.
3. If you run out of memory, try to set `per_device_train_batch_size` to `1`.
4. Set the `num_train_epochs` to a bigger one like `5`.

Besides, would you report what framework (like vLLM, SGLang) is used to host reward models?

**Comment by Elysia-afk** [comment]
Thanks for your reply. 
I have made changes based on your advice. But have little progress.
I follow all settings you mentioned in the paper by **llama_factory**.

The result after 3 epochs are:
{'MN': 0.48, 'CR': 0.6333333333333334, 'CD': 0.5933333333333333, 'FA': 0.7333333333333334}
after 5 epochs are:
{'MN': 0.6249999999999999, 'CR': 0.42500000000000004, 'CD': 0.7166666666666666, 'FA': 0.8}

I thought the key point is the cutoff_len, however it does not work even I have set it as 8196. I also investigate performance in different inference temperatures, it shows that temperature has little influence.

As I mentioned that you use 1.5h for training, however I **only cost 20 min**, so I wonder whether there is any technique gap between us, which could cause the difference. 

Here is the manipulated file.
```yaml
### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: /dataset/reward_data/
dataset: trainset_reward_llama
template: llama3
cutoff_len: 8096
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3_1-8b_bsft/full/sft
logging_steps: 10
save_steps: 84
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-5                                         
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
save_only_model: true
```

I would appreciate it if you could help.
>

**Comment by luyaxi** [comment]
Happy New Year First!
Here are the settings we used to train our reward model. 

```yaml
### model
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct/

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: active_rmllama
template: llama3
cutoff_len: 8192
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

## output
output_dir: saves/llama3-8b-re/full/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
```

We rerun the training and get following scores:
```text
Final result:
Missed-Need (MN) 0.8
Correct-Rejection (CR) 0.9333333333333333
Correct-Detection (CD) 0.9666666666666667
False-Alarm (FA) 1.0
Average: 0.925
Confusion Matrix:
{'TP': 57, 'FP': 6, 'TN': 54, 'FN': 3}
Accuracy: 0.925
Precision: 0.9047619047619048
Recall: 0.95
F1: 0.926829268292683
```


Besides, we are uploading the reward model to the huggingface.
As for the training time, the `1.5` Hour is the worst estimation with CPU Offloading.
